"""Add output_format column to ResearchProfile

Revision ID: 43ffffaa6ece
Revises: cdf5a2ec94d8
Create Date: 2025-03-18 21:12:45.996473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ffffaa6ece'
down_revision = 'cdf5a2ec94d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_format', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('output_format')

    # ### end Alembic commands ###
