"""Add crawl_depth and max_crawl_pages to ResearchProfile

Revision ID: 4bff34235c2c
Revises: 70e6565fd69b
Create Date: 2025-03-16 16:06:02.347658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bff34235c2c'
down_revision = '70e6565fd69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crawl_depth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_crawl_pages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('max_crawl_pages')
        batch_op.drop_column('crawl_depth')

    # ### end Alembic commands ###
