"""Add active_task_id to ResearchProfile

Revision ID: 517cfea2810b
Revises: 890f286db57f
Create Date: 2025-03-19 11:52:45.813792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517cfea2810b'
down_revision = '890f286db57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_task_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('translate_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translate_to', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('active_task_id')

    # ### end Alembic commands ###
