"""Add new columns

Revision ID: 70e6565fd69b
Revises: df33cb677eb8
Create Date: 2025-03-16 15:00:45.201944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e6565fd69b'
down_revision = 'df33cb677eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_tld', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('minimum_pdfs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('minimum_pdfs')
        batch_op.drop_column('site_tld')

    # ### end Alembic commands ###
