"""Add topics_and_subtopics column to ResearchProfile

Revision ID: 71cbbb0b34cd
Revises: 517cfea2810b
Create Date: 2025-03-25 22:25:19.210432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cbbb0b34cd'
down_revision = '517cfea2810b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics_and_subtopics', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('topics_and_subtopics')

    # ### end Alembic commands ###
