"""Add max_references_per_subtopic column

Revision ID: 7bf6dc321d95
Revises: 8e13795dbf5f
Create Date: 2025-03-17 13:48:06.460301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf6dc321d95'
down_revision = '8e13795dbf5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_references_per_subtopic', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('max_references_per_subtopic')

    # ### end Alembic commands ###
