"""Add translate_to column

Revision ID: 890f286db57f
Revises: 43ffffaa6ece
Create Date: 2025-03-19 08:30:49.386281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f286db57f'
down_revision = '43ffffaa6ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translate_to', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('translate_to')

    # ### end Alembic commands ###
