"""Add search_purpose and require_pdfs to ResearchProfile

Revision ID: 8e13795dbf5f
Revises: 4bff34235c2c
Create Date: 2025-03-16 16:42:33.659097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e13795dbf5f'
down_revision = '4bff34235c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_purpose', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('require_pdfs', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('require_pdfs')
        batch_op.drop_column('search_purpose')

    # ### end Alembic commands ###
