"""Remove max_references_per_subtopic column

Revision ID: cdf5a2ec94d8
Revises: 7bf6dc321d95
Create Date: 2025-03-17 13:55:59.398874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf5a2ec94d8'
down_revision = '7bf6dc321d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.drop_column('max_references_per_subtopic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_references_per_subtopic', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
